---
title: "01_Getting_&_Knowing_Your_Data -> Chipotle"
output: 
  html_document:
    toc: FALSE
---

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries
```{python}
import pandas as pd
import numpy as np
```

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 

### Step 3. Assign it to a variable called chipo.
```{python}
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep= '\t')
```

### Step 4. See the first 10 entries
```{python}
chipo.head(10)
```

### Step 5. What is the number of observations in the dataset?
```{python}
# Solution 1

chipo.shape
```
```{python}
# Solution 2

chipo.info()
```

### Step 6. What is the number of columns in the dataset?
```{python}
chipo.shape[1]
```

### Step 7. Print the name of all the columns.
```{python}
chipo.head(0)
##chipo.columns   
```

### Step 8. How is the dataset indexed?
```{python}
chipo.index
```

### Step 9. Which was the most-ordered item? 
```{python}
chipo.groupby(by="item_name").sum().sort_values('quantity',ascending=False).head(1)
```

### Step 10. For the most-ordered item, how many items were ordered?
```{python}
chipo.groupby(by="item_name").sum().sort_values('quantity',ascending=False).head(1)
```

### Step 11. What was the most ordered item in the choice_description column?
```{python}
chipo.groupby(by="choice_description").sum().sort_values('quantity',ascending=False).head(1)
```

### Step 12. How many items were orderd in total?
```{python}
chipo.item_name.count()
```

### Step 13. Turn the item price into a float
#### Step 13.a. Check the item price type
```{python}
chipo.item_price.dtype
```
#### Step 13.b. Create a lambda function and change the type of item price
```{python}
dollarizer = lambda x: float(x[1:-1])
chipo.item_price = chipo.item_price.apply(dollarizer)
```
#### Step 13.c. Check the item price type
```{python}
chipo.item_price.dtype
```

### Step 14. How much was the revenue for the period in the dataset?
```{python}
revenue =  (chipo.item_price * chipo.quantity).sum()
print('Revenue is : $ '+ str(revenue))
```

### Step 15. How many orders were made in the period?
```{python}
chipo.order_id.value_counts().count()
```

### Step 16. What is the average revenue amount per order?
```{python}
# Solution 1

chipo['revenue'] = chipo['quantity'] * chipo['item_price']
order_grouped = chipo.groupby(by=['order_id']).sum()
order_grouped['revenue'].mean()
```

### Step 17. How many different items are sold?
```{python}
chipo.item_name.value_counts().count()
```