---
title: "01_Getting_&_Knowing_Your_Data -> Occupation"
output: 
  html_document:
    toc: FALSE
---

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries
```{python}
import pandas as pd
```

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

### Step 3. Assign it to a variable called users and use the 'user_id' as index
```{python}
users = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user', 
                      sep='|', index_col='user_id')
```

### Step 4. See the first 25 entries
```{python}
users.head(25)
```

### Step 5. See the last 10 entries
```{python}
users.tail(10)
```

### Step 6. What is the number of observations in the dataset?
```{python}
users.shape[0]
```

### Step 7. What is the number of columns in the dataset?
```{python}
users.shape[1]
```

### Step 8. Print the name of all the columns.
```{python}
users.columns
```

### Step 9. How is the dataset indexed?
```{python}
# "the index" (aka "the labels")
users.index
```

### Step 10. What is the data type of each column?
```{python}
users.dtypes
```

### Step 11. Print only the occupation column
```{python}
users.occupation

#or

users['occupation']
```

### Step 12. How many different occupations are in this dataset?
```{python}
users.occupation.nunique()
#or by using value_counts() which returns the count of unique elements
#users.occupation.value_counts().count()
```

### Step 13. What is the most frequent occupation?
```{python}
#Because "most" is asked
users.occupation.value_counts().head(1).index[0]

#or
#to have the top 5

# users.occupation.value_counts().head()
```

### Step 14. Summarize the DataFrame.
```{python}
users.describe() #Notice: by default, only the numeric columns are returned. 
```

### Step 15. Summarize all the columns
```{python}
users.describe(include = "all") #Notice: By default, only the numeric columns are returned.
```

### Step 16. Summarize only the occupation column
```{python}
users.occupation.describe()
```

### Step 17. What is the mean age of users?
```{python}
users.age.mean()
```

### Step 18. What is the age with least occurrence?
```{python}
users.age.value_counts().tail() #7, 10, 11, 66 and 73 years -> only 1 occurrence
```